# Site settings
title: Sampath Dev Work Blog
email: sampath_bt@yahoo.com
description: > # Sampath Thennakoon
  About Me - Sampath Thennakoon 
  I am a Senior Software Engineer at Intervest Software Technologies (pvt) Ltd , a company that is at the
  travel insurance products and tools revolution.I am also an Java Community Expert as well as an Java Certified Professional.
  My fields of interest are Go , Java , JavaScript , NoSQL , industry automation, artificial neural networks,
  image processing, distributed computing, artificial intelligence.
baseurl: ""
url: "https://sampathsl.github.io"
twitter_username: sampath_sl
github_username:  sampathsl

# Build settings
markdown: kramdown

gems:
    - jekyll-minifier